#!/bin/bash
cfg=onedrive-taura-kenjiro-gmail-com
dir=onedrive
mkdir -p ${dir}
rclone config reconnect ${cfg}:
rclone mount --daemon --vfs-cache-mode full --write-back-cache --default-permissions ${cfg}: ${dir}
